apiVersion: v1
kind: Pod
metadata:
  name: postgress-db
  labels:
    name: postgress-db
spec:
  containers:
    - name: postgres-db-pod
      image: postgres
      ports:
        - containerPort: 5432
