apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: postgress-db
    app: demo-voting-app
spec:
  containers:
    - name: postgres-db-pod
      image: postgres
      ports:
        - containerPort: 5432
