apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    name: postgress-db
    app: demo-voting-app
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30008
