apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
spec:
  type: NodePort
  selector:
    name: redis-db
    app: demo-voting-app
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30009
    
