apiVersion: v1
kind: Pod
metadata:
  name: redis-db
  labels:
    name: redis-db
    app: demo-voting-app
spec:
  containers:
    - name: redis-db-pod
      image: redis
      ports:
        - containerPort: 6379
