apiVersion: v1
kind: Pod
metadata:
  name: worker-app
  labels:
    name: worker-app
    app: demo-voting-app
spec:
  containers:
  - name: worker-app-pod
    image: kodekloud/examplevotingapp_worker:v1
