apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: yuval_app
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: nginx-2
      labels:
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx