apiVersion: v1
kind: Service
metadata:
  name: myportservice
  labels:
    name: yuvali
    side: backend
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
      type: frontend
