apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
      app: yuval
      type: frontend
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3

